// <auto-generated />
namespace testEmpty2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialMegration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialMegration));
        
        string IMigrationMetadata.Id
        {
            get { return "201804052135132_initialMegration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
